from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional


# ---------------------------------------------------------------------------
# Webhook / Ingestion
# ---------------------------------------------------------------------------

class WebhookPayload(BaseModel):
    """Incoming message payload received from the CRM webhook."""

    client_id: str = Field(
        ...,
        min_length=1,
        description="Unique identifier of the client in the CRM.",
        examples=["CRM-001"],
    )
    message: str = Field(
        ...,
        min_length=1,
        description="Raw message content sent by the client.",
        examples=["This is urgent! My order arrived damaged and I want a refund!"],
    )
    timestamp: datetime = Field(
        ...,
        description="ISO 8601 timestamp indicating when the message was sent.",
        examples=["2024-01-15T10:00:00Z"],
    )


# ---------------------------------------------------------------------------
# Processing Response (shared by webhook + supervisor)
# ---------------------------------------------------------------------------

class ProcessingResponse(BaseModel):
    """Standard API response returned after processing a message or a decision."""

    run_id: str = Field(..., description="Unique identifier for this processing run.")
    status: str = Field(
        ...,
        description=(
            "Current status: 'processed' | 'pending_approval' | "
            "'approved_and_executed' | 'rejected'"
        ),
    )
    sentiment: str = Field(..., description="Detected sentiment: positive | neutral | negative.")
    intent: str = Field(..., description="Detected intent: refund_request | support_request | general_inquiry.")
    sla_breached: bool = Field(..., description="Whether the SLA threshold was exceeded.")
    proposed_action: str = Field(..., description="Action proposed by the Triage agent.")
    supervisor_note: Optional[str] = Field(
        None, description="Briefing note generated by Triage for the human supervisor (escalations only)."
    )
    execution_result: Optional[str] = Field(
        None, description="Personalised response drafted by the Executor agent (if executed)."
    )
    message: str = Field(..., description="Human-readable summary of the outcome.")


# ---------------------------------------------------------------------------
# Supervisor
# ---------------------------------------------------------------------------

class PendingApprovalItem(BaseModel):
    """Summary of a single item waiting for human supervisor approval."""

    run_id: str
    client_id: str
    message: str
    sentiment: str
    sla_breached: bool
    proposed_action: str
    supervisor_note: Optional[str] = Field(
        None, description="Briefing note from Triage to help the supervisor make a decision."
    )
    suggested_response: Optional[str] = Field(
        None, description="Draft response suggested by the system for the supervisor to review."
    )
    timestamp: str


class SupervisorDecision(BaseModel):
    """Decision payload submitted by the human supervisor."""

    run_id: str = Field(..., description="The run ID of the pending action to decide on.")
    approved: bool = Field(..., description="True to approve and execute; False to reject.")
    manual_response: Optional[str] = Field(
        None,
        description=(
            "If provided and approved=True, this text is sent verbatim to the client, "
            "overriding the system's suggested response."
        ),
    )
    reason: Optional[str] = Field(
        None, description="Optional free-text reason for the decision."
    )


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

class SentimentCount(BaseModel):
    """Count and share for one sentiment bucket."""

    sentiment: str
    count: int
    percentage: float


class IntentCount(BaseModel):
    """Count and share for one intent bucket."""

    intent: str
    count: int
    percentage: float


class ActionCount(BaseModel):
    """Count and share for one proposed-action bucket."""

    action: str
    count: int
    percentage: float


class ClientStat(BaseModel):
    """Per-client aggregated activity."""

    client_id: str
    total: int
    negative_count: int
    sla_breached_count: int


class MetricsSummary(BaseModel):
    """Top-level aggregated statistics returned by the metrics endpoint."""

    total_messages: int = Field(..., description="Total messages processed since the system started.")
    escalation_rate: float = Field(..., description="Percentage of messages escalated to a human supervisor.")
    sla_breach_rate: float = Field(..., description="Percentage of messages that breached the SLA threshold.")
    approval_rate: float = Field(..., description="Percentage of escalated messages that were approved (0 if none escalated).")
    pending_approvals: int = Field(..., description="Number of messages currently waiting for a supervisor decision.")
    sentiment_distribution: list[SentimentCount]
    intent_distribution: list[IntentCount]
    action_distribution: list[ActionCount]
    top_clients: list[ClientStat] = Field(..., description="Top 10 clients by message volume.")
